// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDABEJxVeCwNUUa-uhkVIB_mQ0fgB-Eluo',
    appId: '1:618633157773:web:ffc861d297cb4bda3e96c4',
    messagingSenderId: '618633157773',
    projectId: 'tre-sastronautas',
    authDomain: 'tre-sastronautas.firebaseapp.com',
    storageBucket: 'tre-sastronautas.appspot.com',
    measurementId: 'G-RJFVNXWDJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ99c2RA4H6B_ZyQQiw5CqX7lyHJH1rPU',
    appId: '1:618633157773:android:d688a447487cdf2e3e96c4',
    messagingSenderId: '618633157773',
    projectId: 'tre-sastronautas',
    storageBucket: 'tre-sastronautas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDddTxxOJgCOd30KfyDwzIT9RchH7VU_IM',
    appId: '1:618633157773:ios:38c4c2040bf94cb93e96c4',
    messagingSenderId: '618633157773',
    projectId: 'tre-sastronautas',
    storageBucket: 'tre-sastronautas.appspot.com',
    iosBundleId: 'com.example.tresAstronautas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDddTxxOJgCOd30KfyDwzIT9RchH7VU_IM',
    appId: '1:618633157773:ios:38c4c2040bf94cb93e96c4',
    messagingSenderId: '618633157773',
    projectId: 'tre-sastronautas',
    storageBucket: 'tre-sastronautas.appspot.com',
    iosBundleId: 'com.example.tresAstronautas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDABEJxVeCwNUUa-uhkVIB_mQ0fgB-Eluo',
    appId: '1:618633157773:web:5050ee6ef5e39ec03e96c4',
    messagingSenderId: '618633157773',
    projectId: 'tre-sastronautas',
    authDomain: 'tre-sastronautas.firebaseapp.com',
    storageBucket: 'tre-sastronautas.appspot.com',
    measurementId: 'G-G884CQPLMC',
  );
}
